name: cars
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.2
  carousel_slider: ^4.2.1

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.1.5
  fluttertoast: ^8.0.9
  image_picker: ^0.8.6

  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
